### ISSUE TITLE
echarts.graphic.LinearGradient not working

### ISSUE THREAD

**Issue by andfanilo** [andfanilo/streamlit-echarts#10]
```
color: new echarts.graphic.LinearGradient(
                    0, 0, 0, 1,
                    [
                        {offset: 0, color: '#83bff6'},
                        {offset: 0.5, color: '#188df0'},
                        {offset: 1, color: '#188df0'}
                    ]
                )
```

doesn't work. I suppose the `echarts` namespace was minified and doesn't exist anymore?

https://echarts.apache.org/examples/en/editor.html?c=bar-gradient

**Comment by liunux4odoo** [comment]
yes, you are right, the global variable `echarts` does not exist anymore after webpacking, so the `LinearGradient` will not work with the built chunks.
variable `echarts` has lots of APIs that can be set to chart option in runtime. In webpack environment, you can only use them when developing , e.g. `echarts.registerMap`, in build chunks it does not exist either.

**Comment by andfanilo** [comment]
Yeah, which is too bad :( 

I wanted to try referring back to the [echarts instance through a ref](https://github.com/hustcc/echarts-for-react#component-api--echarts-api) but the Streamlit lifecycle makes it hard to go back and forth between Python and JS afterwards anyway _(absolutely not easy to do streamlit_echarts.setOption or streamlit_echarts.registerMap after the component was set, everything must be done when initializing the component and then eventually rerunning the script by changing component arguments to animate between 2 states)_

Thanks for your comment, it helped reinforce my thoughts about it :) I may close this soon as "Unresolved"

Fanilo

**Comment by andfanilo** [comment]
Actually I'll close this in favor of #4
