### ISSUE TITLE
Does Pyecharts Map chart need to follow echarts sample

### ISSUE THREAD

**Issue by franklighter** [andfanilo/streamlit-echarts#16]
python3.6.3
streamlit 0.82.0
streamlit-echarts 0.3.0

on Pyecharts, the MAP chart can be loaded 

```
from pyecharts.charts import Map
from pyecharts.faker import Faker
from pyecharts import options as opts

demoMap = Map(init_opts=opts.InitOpts(bg_color='white'))
demoMap.add("Demo", [list(z) for z in zip(Faker.country, Faker.values())], "world")
demoMap.render("demo.html")
```

Using streamlit-echarts, the same cannot load the map but just I can see chart legend in streamlit, just no map is shown nor error msg.
```
st_pyecharts(chart=demoMap)
```
Does it need to follow echarts sample, e.g. load JSON file, etc because pyecharts has simplified those geo data already.

There is no issue to load Bar chart and its content in streamlit.

thank you

**Comment by andfanilo** [comment]
Hello @franklighter,

The `demoMap.render(...)` builds an HTML file where the `world` map data is downloaded at initialization (you will see `<script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/world.js"></script>` in the HTML result). For now the `streamlit-echarts` library needs you to do this initialization manually through the `map` parameter.

### Technique 1 (official)

1. Download [the world geojson data](https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json).
2. Load it in Python and pass it to the `map` parameter:

```python
import json

from pyecharts import options as opts
from pyecharts.charts import Map
from pyecharts.faker import Faker
from streamlit_echarts import Map as st_Map
from streamlit_echarts import st_pyecharts

with open("./data/countries.geo.json", "r") as f:
    map = st_Map("world", json.loads(f.read()),)
demoMap = Map(init_opts=opts.InitOpts(bg_color="white"))
demoMap.add("Demo", [list(z) for z in zip(Faker.country, Faker.values())], "world")
demoMap.set_series_opts(label_opts=opts.LabelOpts(is_show=False))
demoMap.set_global_opts(
    title_opts=opts.TitleOpts(title="Map world"),
    visualmap_opts=opts.VisualMapOpts(max_=200),
)
st_pyecharts(demoMap, map=map, height=500)
```

### Technique 2 (backup plan)

Render the HTML directly with `components.html`:

```python
import streamlit.components.v1 as components
from pyecharts import options as opts
from pyecharts.charts import Map
from pyecharts.faker import Faker

demoMap = Map(init_opts=opts.InitOpts(bg_color='white'))
demoMap.add("Demo", [list(z) for z in zip(Faker.country, Faker.values())], "world")
components.html(demoMap.render_embed(), width=1000, height=1000)
```

Hope this helps, happy Streamlit-ing :balloon:
Fanilo
