### ISSUE TITLE
Add suport for st.columns()

### ISSUE THREAD

**Issue by felipejardimf** [andfanilo/streamlit-echarts#18]
Hey!

Is it possible to use this wonderful lib with the st.column() notation in Streamlit?
Tried and returned an error.

Thanks!!

**Comment by andfanilo** [comment]
Hey @felipejardimf ,

Not tested but does 

```python
c1, c2 = st.columns(2)
with c2: 
    st_echarts(...)
```

work? If it doesn't what is the traceback error?

Thanks in advance,
Fanilo

**Comment by felipejardimf** [comment]
Just tested here ! 
It works !

thank you soo much, @andfanilo !
Felipe

**Comment by andfanilo** [comment]
Your welcome !
