### ISSUE TITLE
Chart Height is constant even when setting its height with in initOpts

### ISSUE THREAD

**Issue by avivazran** [andfanilo/streamlit-echarts#26]
charts are outputted in streamlit app in constant size which makes them sometimes unreadable.
```python
c = Line(init_opts=opts.InitOpts(theme=ThemeType.DARK, height='1600px', width='1600px'))
```

![image](https://user-images.githubusercontent.com/39994570/147204719-10e3cb99-d201-4886-b93f-fb44cca8306b.png)

unlike the stock visualization components of streamlit, the echarts components doesn't have the 'extend' button which the other components have and enables full screen view of the chart.

I know that this probably a streamlit related issue rather than to this package, however - if there is a way to force the chart height or at least add a full screen view option that will be great.

Thanks

**Comment by andfanilo** [comment]
Hello @avivazran !

Unfortunately the Pyecharts `InitOpts` don't seem to be passed as options to echarts, so `theme=ThemeType.DARK, height='1600px', width='1600px'` need to be passed at the `st_pyecharts` call instead to be used.

```python

c = (
    Line()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
)
st_pyecharts(c, theme=ThemeType.DARK, height="1600px", width="1600px")
```

I'm also looking into an issue on resizing the chart for responsive design for #27 and #28.

Have a nice day,
Fanilo
