### ISSUE TITLE
Render html from st_echarts (not st_pyecharts)

### ISSUE THREAD

**Issue by Filhomn** [andfanilo/streamlit-echarts#39]
This package is really great! The st_echarts is even better than pyecharts! Because it is much more versatile, and we can use the echarts.js documentation as reference! Which was the main advantage of using R over Python for echarts.  Is it possible to render local html from st_echarts? So we can use it in general not just with streamlit..

Kinds Regards,

**Comment by andfanilo** [comment]
Hey @Filhomn 

Haven't tested but I think pyecharts's `.render_embed()` does that, unfortunately I did not find a way to easily download the graph as HTML in native eCharts that I can copy to streamlit_echarts 🤔 if you find a link I would gladly read it!

Have a nice day,
Fanilo
