### ISSUE TITLE
Add Timeline, 3D, dataZoom demo

### ISSUE THREAD

**Issue by EricJoung1997** [andfanilo/streamlit-echarts#40]
Hello, thank you for incrediable job!
Is it possible to add these demos：
- Timeline, like this https://echarts.apache.org/examples/zh/editor.html?c=scatter-life-expectancy-timeline
- dataZoom, like this https://echarts.apache.org/examples/zh/editor.html?c=custom-ohlc
- 3D plot, like this https://echarts.apache.org/examples/zh/editor.html?c=scatter3d&gl=1&theme=dark

**Comment by andfanilo** [comment]
Hey @EricJoung1997, 

I won't be able to look at this until some months unfortunately. Have you tried implementing those on your side? It's a challenge of converting JS code to Python code mostly (and trying to figure out what to replace api.fn with) I would gladly merge them if you succeed in implementing them :) 

If you need to download the dataset like `$.get(ROOT_PATH + '/data/asset/data/life-expectancy.json'`, you can usually add | `console.log(data)` in the JS console and get back the data in your browser console inspector, or I think they are in https://github.com/apache/echarts/tree/master/test/data

Have a nice day,
Fanilo

**Comment by EricJoung1997** [comment]
I will try my best
