### ISSUE TITLE
use streamlit-echarts doesn't show pyecharts in iphone safari or chrome

### ISSUE THREAD

**Issue by dawaylee** [andfanilo/streamlit-echarts#5]
use streamlit-echarts doesn't show pyecharts in iphone safari or chrome
but in chrome of pc is ok!

**Comment by andfanilo** [comment]
Hey @dawaylee, thanks for reporting, I'll look into it this month :) though if you already have an idea how to display echarts on mobile I'm open to hearing it !

Cheers,
Fanilo

**Comment by dawaylee** [comment]
Hello, I'll describe the problem I'm having. I'm using st_pyecharts to display charts that work fine in Chrome on my PC, but the same pages don't display properly when I access them with my mobile browser, whether it's Chrome, safari or any other mobile browser, but when I access the official pyecharts sample address with my mobile browser, the charts display normally.

Please help answer this question, thanks!

**Comment by dawaylee** [comment]
Thank you very much for your reply, because I prefer to use streamlit, the chart I used to use more is plotly, but always wanted to use echarts in streamlit, especially after having pyecharts, and after discovering your streamlit-echarts, I was very surprised to experience it, thank you for your efforts!

**Comment by andfanilo** [comment]
Yes sounds odd for me too. Can you perhaps share a small example that I can reproduce on my side?

Fanilo

**Comment by dawaylee** [comment]
For example, the following URL, which is an official demo of pyecharts, will display the chart properly if you open it with your mobile browser. https://gallery.pyecharts.org/#/Bar/mixed_bar_and_line

The website address I made with streamlit is www.futurepat.com. If you open it with your mobile browser and click [3.******] in the left navigation menu, the chart on the right will not show up properly. These charts are generated by st.pyecharts of streamlit-echarts, which can be opened normally by a computer browser.

**Comment by dawaylee** [comment]
Today, I suddenly found that it is my phone problems caused by the display does not appear, I use the phone is iphone x, ios version 13.5, safari and download the latest chrome can not be displayed properly, it seems to upgrade the version to try it.

**Comment by andfanilo** [comment]
Hey! Sorry for the late reply. I'll be closing this then, feel free to reopen if you bump into new problems!
Fanilo
