### ISSUE TITLE
small typo on docs front page

### ISSUE THREAD

**Issue by aarong1** [andfanilo/streamlit-echarts#50]
I notice a small typo regarding the use of .js_code 
The context and proposed fix are outlined in this PR

https://github.com/andfanilo/streamlit-echarts/pull/49

Thank you for all your outrageous work on this. The package looks fantastic

Best, Aaron

**Comment by andfanilo** [comment]
Ooooops, thanks for the fix :) merged!

Have a nice day!

**Comment by aarong1** [comment]
> Ooooops, thanks for the fix :) merged!
> 
> Have a nice day!

You too!
