### ISSUE TITLE
Is it possible to have an echart chart inside a streamlit column?

### ISSUE THREAD

**Issue by M4thinking** [andfanilo/streamlit-echarts#56]
Is it possible to set an echart chart within a column or a row like in streamlit charts? 

Example of streamlit:

col1, col2 = st.columns(2)
data = ...
col1.line_chart(data)

**Comment by andfanilo** [comment]
Yes! instead of col1.line_chart, you can do:

```python
with col1:
    st.line_chart()
```

same with echarts

```python
with col1:
    st_echarts(...)
```

It should work, do tell meif there's an issue there, since I'm not on my code computer 🤔

**Comment by M4thinking** [comment]
It worked, I am new to this, thank you!!
