### ISSUE TITLE
echarts 5 support

### ISSUE THREAD

**Issue by andfanilo** [andfanilo/streamlit-echarts#6]
Still waiting for https://github.com/hustcc/echarts-for-react/issues/388 

A user wanted a demo of [gauge ring](https://echarts.apache.org/next/examples/en/editor.html?c=gauge-ring) in Streamlit

**Comment by CharlyWargnier** [comment]
Looks fantastic!

**Comment by andfanilo** [comment]
So echarts-for-react now accepts echarts 5 \o/ I have the thing working on a branch.
We still need to wait a little bit for pyecharts though https://github.com/pyecharts/pyecharts/issues/1754 I don't know how exactly pyecharts works for echarts 5 if I release this now.
