### ISSUE TITLE
Add wordcloud extension

### ISSUE THREAD

**Issue by datalee** [andfanilo/streamlit-echarts#8]
1、if like this , it donot work
b = (
    WordCloud()
    .add(series_name="xxx", data_pair=data)
)
st_pyecharts(b)

2、like this, it works
b = (
    WordCloud()
    .add(series_name="xxx", data_pair=data, word_size_range=[6, 66])
    .render_embed()
)
components.html(b, width=1000, height=1000)

**Comment by andfanilo** [comment]
Hello @datalee, thank you for the feedback :+1: 

It looks like Pyecharts wordcloud uses [an echarts extension](https://github.com/ecomfe/echarts-wordcloud) that I didn't bring to `streamlit-echarts`. Let me add it later to the library!

Cheers,
Fanilo

**Comment by datalee** [comment]
> Hello @datalee, thank you for the feedback 👍
> 
> It looks like Pyecharts wordcloud uses [an echarts extension](https://github.com/ecomfe/echarts-wordcloud) that I didn't bring to `streamlit-echarts`. Let me add it later to the library!
> 
> Cheers,
> Fanilo

tks

**Comment by andfanilo** [comment]
@datalee I just published `streamlit-echarts` v0.2.0, which adds wordcloud and liquidfill. 

Can you upgrade and try again?

**Comment by datalee** [comment]
> streamlit-echarts

yes，works！！！good job
